#!/bin/bash

case $3 in 

add) echo "Addition = $(($1+$2))" ;;
sub) echo "Subtraction = $(($1-$2))" ;;
mul) echo "Multiplication = $(($1*$2))" ;;
div) echo "Division = $(($1/$2))" ;;
esac


### Second case condition

read -p 'Enter first value: ' a
read -p 'Enter second value: ' b

read -p 'Enter operator (add|sub|mul|div): ' op

op=$(echo $op| tr [:upper:] [:lower:]) 

case $op in

add) echo "Addition = $(($a+$b))" ;;
sub) echo "Subtraction = $(($a-$b))" ;;
mul) echo "Multiplication = $(($a*$b))" ;;
div) echo "Division = $(($a/$b))" ;;
*) echo -e "\e[31mInvalid Input\e[0m"
exit 1
esac 
####
case $op in

add) echo "Addition = $(($a+$b))" ;;
sub) echo "Subtraction = $(($a-$b))" ;;
mul) echo "Multiplication = $(($a*$b))" ;;
div) echo "Division = $(($a/$b))" ;;
*) echo -e "\e[31mInvalid Input\e[0m"
exit 1
esac 
add) echo "Addition = $(($a+$b))" ;;
sub) echo "Subtraction = $(($a-$b))" ;;
mul) echo "Multiplication = $(($a*$b))" ;;
div) echo "Division = $(($a/$b))" ;;
*) echo -e "\e[31mInvalid Input\e[0m"
####### echo hello
