#!/bin/bash

## here we would like to see functions restrcited to local only

date=May-20

just(){
echo "Today's date is $date"
local dated=20th-May
}

just

echo -e "\e[33mToday's date is $dated\e[0m"
