#!/bin/bash

usage() {

echo "Usage: $0 val1 val2 operator"

}

if [ $# -ne 3 ]
then
	echo "Invalid input"
	usage
	exit 1
fi

case $3 in
add) echo "Addition = $((a+b))";;
sub) echo "Subtraction =$((a-b))";;
mul) echo "Multiplication = $((a*b))";;
div) echo "Division = $((a/b))";;
*) echo "Invalid input";;
esac
