#!/bin/bash

usage() {

echo "Usage: $(basename $0) val1 val2 operator"

}

if [ $# -ne 3 ]
then
	echo "Invalid input"
	usage
	exit 1
fi

case $3 in
add) echo "Addition = $(($1+$2))";;
sub) echo "Subtraction =$(($1-$2))";;
mul) echo "Multiplication = $(($1*$2))";;
div) echo "Division = $(($1/$2))";;
*) echo "Invalid input";;
esac
