#!/bin/bash

read -p 'Enter your name : ' name
read -p 'Enter your location : ' loc
read -s -p 'Enter your password : ' pass

echo -e "\e[32mHello $name, your location is $loc and your password is $pass\e[0m"



